name: michaeldadzie
description: My Portfolio Website

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  velocity_x: ^0.5.0
  flutter_icons: ^1.1.0
  url_launcher: ^5.7.8
  animated_text_kit: ^2.5.0
  get_it: ^5.0.1
  google_fonts: ^1.1.1
  flutter_hidden_drawer: ^0.1.5
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg

